---
- hosts: all
  connection: local
  become: yes

  pre_tasks:
  - name: S'assurer que le cache APT est à jour.
    apt:
      update_cache: yes
      cache_valid_time: 3600
  
  - name: Ajout d'une clé Oracle 2016
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      state: present
      
  - name: Ajout d'une clé Oracle
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox.asc
      state: present
          
  handlers:
  - name: apt update
    apt:
      update_cache: yes

  - name: apt upgrade
    apt:
      name: "*"
      state: latest


  tasks:
  - name: Ajout du dépot virtualbox.
    apt_repository:
      repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian/ buster contrib
      state: present
      filename: virtualbox
    notify:
      - apt update
      - apt upgrade
